name: elliptic-gnn
channels:
  - conda-forge
  - nvidia          # for other CUDA-related libs if needed
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - shap
  - pytest
  - pyyaml
  - tqdm
  - networkx
  - xgboost
  - tensorboard
  - pip
  - streamlit
  - plotly
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu126   # CUDA 12.6 wheels
      - torch==2.7.0
      - torchvision
      - torchaudio
      - torch-geometric
      - imbalanced-learn

# CPU-only alternative:
# Replace the pip section with:
#  - pip:
#      - torch==2.7.0
#      - torchvision
#      - torchaudio
#      - torch-geometric
#      - imbalanced-learn