
run_name: lr_default
seed: 42
processed_dir: data/processed

model: logistic_regression
calibration: isotonic   # isotonic | platt | none

use_val_for_thresholds: true
precision_target: 0.90  # if >0, choose threshold to hit this precision; else max-F1
topk: 100               # Precision@K on test

C: 1.0
max_iter: 2000
