run_name: lr_default
seed: 42
processed_dir: data/processed

model: logistic_regression
calibration: isotonic

use_val_for_thresholds: true
precision_target: 0.0      # use max-F1 on val
topk: 100

C: 1.0
max_iter: 2000
class_weight: balanced     # helpful on this class imbalance
