run_name: xgb_default
seed: 42
processed_dir: data/processed

model: xgboost
calibration: isotonic      # isotonic | platt | none

use_val_for_thresholds: true
precision_target: 0.0      # use max-F1 on validation
topk: 100                  # Precision@K on test

# core XGB
n_estimators: 1000
max_depth: 4
learning_rate: 0.05
min_child_weight: 5
subsample: 0.8
colsample_bytree: 0.8
eval_metric: aucpr

# early stopping (handled via kwarg or callbacks, auto-detected)
early_stopping_rounds: 50

# handle imbalance
scale_pos_weight: "auto"   # computed from train split

# device: auto via code (CUDA if available)
# tree_method: auto         # keep default; code chooses per version/device
