run_name: gat_w10_time
seed: 42
processed_dir: data/processed

# Model
arch: gat
hidden_dim: 32           # 32 * 4 heads = 128 total width per layer
layers: 2
heads: 4
dropout: 0.5

# Training
lr: 0.003
weight_decay: 0.0001
max_epochs: 300
patience: 60             # GAT can need a bit more patience
grad_clip: 1.0
device: auto
amp: true

# Data/time
symmetrize_edges: false
use_time_scalar: true
train_window_k: 10

# Loss
class_weight_pos: auto
focal_loss: false        # try true if logits are very peaky; add focal_gamma: 2.0

# Evaluation
use_val_for_thresholds: true
precision_target: 0.75
topk: 100

ablate_hubs_frac: 0.0
