run_name: gcn_w10_time
seed: 42
processed_dir: data/processed

# Model
arch: gcn
hidden_dim: 128
layers: 3
dropout: 0.5

# Training
lr: 0.003
weight_decay: 0.0001
max_epochs: 300
patience: 50
grad_clip: 1.0
device: auto
amp: true

# Data/time
symmetrize_edges: false
use_time_scalar: true       # append normalized timestep
train_window_k: 10          # rolling window over the most recent train timesteps

# Loss
class_weight_pos: auto      # inverse-frequency class weights
focal_loss: false           # set true + focal_gamma: 2.0 if you see overconfident logits

# Evaluation
use_val_for_thresholds: true
precision_target: 0.75      # pick threshold to hit this precision on val
topk: 100

# Extras
ablate_hubs_frac: 0.0
