run_name: sage_resbn_k8_sin2_calib
seed: 42
processed_dir: data/processed

device: auto
amp: true
grad_clip: 1.0

arch: sage_resbn
hidden_dim: 64
layers: 3
dropout: 0.20
weight_decay: 5.0e-5
lr: 5.0e-4
max_epochs: 250
patience: 30
mini_batch: false
fanout: [10, 10]
batch_size: 8192

class_weight_pos: auto
focal_loss: false

use_val_for_thresholds: true
precision_target: 0.20     # choose threshold to hit ~20% precision on val
topk: 100

calibrate_temperature: true
ablate_hubs_frac: 0.0
symmetrize_edges: true
use_time_scalar: false
train_window_k: 8

# time features
time_embed_dim: 2
time_embed_type: sin
time_embed_l2: 0.0
time_loss_weighting: none
