name: CI
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install minimal deps (CPU)
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.2.2 --index-url https://download.pytorch.org/whl/cpu
        pip install numpy pandas scikit-learn scipy xgboost pyyaml tqdm networkx matplotlib tensorboard
        pip install torch-geometric==2.5.3
        pip install pytest
    - name: Run tests
      run: pytest -q
